---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: chef/inspec
    tag: latest

inputs:
- name: krill

params:
  CHEF_LICENSE: accept

run:
  path: krill/ci/scripts/inspec.sh